# Generated by Django 5.0.1 on 2024-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('education', models.TextField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, default='def.jpg', null=True, upload_to='images/')),
                ('workExperience', models.TextField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleName', models.CharField(max_length=50)),
                ('scheduleDate', models.CharField(max_length=50)),
                ('scheduleTime', models.CharField(max_length=12)),
            ],
        ),
    ]
